# Site settings
title: PlantCV
baseurl: ''
# url: http://plantcv.danforthcenter.org/

# Build settings
markdown: redcarpet
highlighter: pygments

# Jekyll-Bootstrap
JB:
    version: 2.0.3
    BASE_PATH : http://plantcv.danforthcenter.org/
