# run: conda env create --file environment.yml
# optionally, change channel name with -n {plantcv-dev}
name: plantcv
dependencies:
  - python=3.13
  - matplotlib>=1.5
  - numpy>=2
  - pandas
  - python-dateutil
  - scipy<1.16
  - scikit-image>=0.19
  - scikit-learn
  - dask
  - dask-jobqueue
  - opencv
  - statsmodels
  - xarray>=2022.11.0
  - mkdocs
  - nd2
  - pytest
  - pytest-cov
  - flake8
  - ipympl
  - nodejs
  - jupyterlab
  - altair
  - vl-convert-python
  - git
  - flyr

channels:
  - conda-forge
