# run: conda env create --file environment37.yml
name: test-environment
dependencies:
  - python=3.7
  - matplotlib>=1.5
  - numpy>=1.11
  - pandas
  - python-dateutil
  - scipy
  - scikit-image
  - pytest
  - plotnine
  - coveralls
  - nb_conda
  - pip
  - pip:
    - opencv-python<4, >=3.4
channels:
  - defaults
  - conda-forge
