# run: conda env create --file environment.yml
# optionally, change channel name with -n {plantcv-dev}
name: plantcv
dependencies:
  - python=3.10
  - matplotlib>=1.5,<3.6
  - numpy>=1.11,<1.23
  - pandas<2
  - python-dateutil
  - scipy
  - scikit-image>=0.19
  - scikit-learn
  - plotnine
  - dask
  - dask-jobqueue
  - nb_conda
  - opencv
  - statsmodels
  - mkdocs
  - pytest

channels:
  - conda-forge
  - defaults
