# run: conda env create --file environment.yml
# optionally, change channel name with -n {plantcv-dev}
name: plantcv
dependencies:
  - python=3.11
  - matplotlib>=1.5
  - numpy>=1.11
  - pandas
  - python-dateutil
  - scipy
  - scikit-image>=0.19
  - scikit-learn
  - dask
  - dask-jobqueue
  - opencv
  - statsmodels
  - xarray>=2022.11.0
  - mkdocs
  - pytest
  - pytest-cov
  - flake8
  - ipympl
  - nodejs
  - jupyterlab
  - altair
  - vl-convert-python
  - git

channels:
  - conda-forge
  - defaults
