site_name: PlantCV
site_url: http://plantcv.readthedocs.io/
site_description: Plant phenotyping using computer vision
site_author: PlantCV Development Team
repo_url: https://github.com/danforthcenter/plantcv
copyright: Copyright 2016, Donald Danforth Plant Science Center

pages:
- Home: index.md
- Documentation:
  - 'Installation': installation.md
  - 'Updating PlantCV': updating.md
  - 'Frequently Asked Questions': faq.md
  - 'Analysis Approaches': analysis_approach.md
  - 'Using Jupyter Notebooks': jupyter.md
  - 'Summary of Output Measurements': output_measurements.md
  - 'Contributing':
    - 'Contributing to PlantCV': CONTRIBUTING.md
    - 'Code of Conduct': CODE_OF_CONDUCT.md
    - 'Adding/editing Documentation': documentation.md
  - Tutorials:
    - 'VIS pipeline': vis_tutorial.md
    - 'NIR pipeline': nir_tutorial.md
    - 'PSII pipeline': psII_tutorial.md
    - 'VIS/NIR dual pipeline': vis_nir_tutorial.md
    - 'Multi plant pipeline': multi-plant_tutorial.md
    - 'Machine Learning': machine_learning_tutorial.md
    - 'Pipeline parallelization': pipeline_parallel.md
    - 'Exporting data': db-exporter.md
  - 'Package plantcv':
    - 'Adaptive Threshold': adaptive_threshold.md
    - 'Analyze color': analyze_color.md
    - 'Analyze NIR': analyze_NIR_intensity.md
    - 'Analyze PSII': fluor_fvfm.md
    - 'Analyze shape': analyze_shape.md
    - 'Apply mask': apply_mask.md
    - 'Auto Crop': auto_crop.md
    - 'Background Subtraction': background_subtraction.md
    - 'Binary threshold': binary_threshold.md
    - 'Boundary line tool': analyze_bound.md
    - 'Cluster Contours': cluster_contours.md
    - 'Cluster Contours and Split Images': cluster_contours_splitimg.md
    - 'Color palette': color_palette.md
    - 'Crop and Position Mask': crop_position_mask.md
    - 'Dilation': dilate.md
    - 'Erosion': erode.md
    - 'Fill objects': fill.md
    - 'Find objects': find_objects.md
    - 'Flip image': flip.md
    - 'Gaussian Blur': gaussian_blur.md
    - 'Get NIR images': get_nir.md
    - 'Erosion': erode.md
    - 'Fill objects': fill.md
    - 'Find objects': find_objects.md
    - 'Histogram normalization': HistEqualization.md
    - 'Image add': image_add.md
    - 'Image subtract': image_subtract.md
    - 'Invert': invert.md
    - 'Landmark Analysis':
      - 'Acute Vertex': acute_vertex.md
      - 'x-Axis Pseudolandmarks': x_axis_pseudolandmarks.md
      - 'y-Axis Pseudolandmarks': y_axis_pseudolandmarks.md
      - 'Scale Features': scale_features.md
      - 'Landmark Reference Point Distribution': landmark_reference_pt_dist.md
    - 'Laplace filter': laplace_filter.md
    - 'Logical operations-And': logical_and.md
    - 'Logical operations-Or': logical_or.md
    - 'Median blur': median_blur.md
    - 'Naive Bayes classifier': naive_bayes_classifier.md
    - 'Object composition': object_composition.md
    - 'Otsu Auto Threshold': otsu_threshold.md
    - 'Output Mask': output_mask.md
    - 'Plot histogram': plot_hist.md
    - 'Print image': print_image.md
    - 'Read image': read_image.md
    - 'Rectangle mask': rectangle_mask.md
    - 'Region of interest-Define': define_roi.md
    - 'Region of interest-Objects': roi_objects.md
    - 'Report Size Marker': report_size_marker.md
    - 'Resize': resize.md
    - 'RGB to HSV': rgb2hsv.md
    - 'RGB to LAB': rgb2lab.md
    - 'Rotate Image': rotate.md
    - 'Shift Image': shift.md
    - 'Sobel filter': sobel_filter.md
    - 'Triangle Auto Threshold': triangle_threshold.md
    - 'Watershed Segmentation': watershed.md
    - 'White balance': white_balance.md
  - 'Package plantcv.learn':
    - 'Naive Bayes': naive_bayes.md
    - 'Naive Bayes Multiclass': naive_bayes_multiclass.md
markdown_extensions:
  - toc:
      permalink: True
