site_name: PlantCV
site_url: http://plantcv.readthedocs.io/
site_description: Plant phenotyping using computer vision
site_author: PlantCV Development Team
repo_url: https://github.com/danforthcenter/plantcv
copyright: Copyright 2016, Donald Danforth Plant Science Center
theme: readthedocs

nav:
- Home: index.md
- Documentation:
  - 'Installation': installation.md
  - 'Updating PlantCV': updating.md
  - 'Frequently Asked Questions': faq.md
  - 'Analysis Approaches': analysis_approach.md
  - 'Using Jupyter Notebooks': jupyter.md
  - 'Summary of Output Measurements': output_measurements.md
  - 'Contributing':
    - 'Contributing to PlantCV': CONTRIBUTING.md
    - 'Code of Conduct': CODE_OF_CONDUCT.md
    - 'Adding/Editing Documentation': documentation.md
  - Tutorials:
    - 'VIS Workflow': vis_tutorial.md
    - 'NIR Workflow': nir_tutorial.md
    - 'PSII Workflow': psII_tutorial.md
    - 'VIS/NIR Dual Workflow': vis_nir_tutorial.md
    - 'Multi Plant Workflow': multi-plant_tutorial.md
    - 'Machine Learning': machine_learning_tutorial.md
    - 'Workflow Parallelization': pipeline_parallel.md
    - 'Exporting Data': db-exporter.md
    - 'Color Correction Workflow': transform_color_correction_tutorial.md
    - 'Morphology Workflow': morphology_tutorial.md
    - 'Thermal Workflow': thermal_tutorial.md
    - 'Hyperspectral Workflow': hyperspectral_tutorial.md
  - 'Package Plantcv':
    - 'Analyze color': analyze_color.md
    - 'Analyze NIR': analyze_NIR_intensity.md
    - 'Analyze PSII': fluor_fvfm.md
    - 'Analyze Shape': analyze_shape.md
    - 'Analyze Thermal': analyze_thermal_values.md
    - 'Apply Mask': apply_mask.md
    - 'Auto Crop': auto_crop.md
    - 'Background Subtraction': background_subtraction.md
    - 'Boundary Line Tool':
      - 'Horizontal Boundary Tool': analyze_bound_horizontal.md
      - 'Vertical Boundary Tool': analyze_bound_vertical.md
    - 'Canny Edge Detection': canny_edge_detect.md
    - 'Closing': closing.md
    - 'Cluster Contours': cluster_contours.md
    - 'Cluster Contours and Split Images': cluster_contours_splitimg.md
    - 'Color Palette': color_palette.md
    - 'Color Transformations':
      - 'Correct Color': transform_correct_color.md
      - 'RGB to Gray': rgb2gray.md
      - 'RGB to LAB': rgb2lab.md
      - 'RGB to HSV': rgb2hsv.md
      - 'White balance': white_balance.md
    - 'Crop and Position Mask': crop_position_mask.md
    - 'Dilation': dilate.md
    - 'Distance Transform': distance_transform.md
    - 'Erosion': erode.md
    - 'Fill Objects': fill.md
    - 'Fill Holes': fill_holes.md
    - 'Find Objects': find_objects.md
    - 'Flip Image': flip.md
    - 'Filters':
      - 'Laplace Filter': laplace_filter.md
      - 'Sobel Filter': sobel_filter.md
      - 'Scharr Filter': scharr_filter.md
    - 'Gaussian Blur': gaussian_blur.md
    - 'Get Kernel': get_kernel.md
    - 'Get NIR Images': get_nir.md
    - 'Histogram Normalization': HistEqualization.md
    - 'Hyperspectral Sub-Package':
        - 'Analyze index': analyze_index.md
        - 'Analyze spectral': analyze_spectral.md
        - 'Calibrate': calibrate.md
        - 'Extract index': extract_index.md
        - 'Extract wavelength': extract_wavelength.md
    - 'Image Add': image_add.md
    - 'Image Subtract': image_subtract.md
    - 'Invert': invert.md
    - 'Landmark Analysis':
      - 'Acute Vertex': acute_vertex.md
      - 'x-Axis Pseudolandmarks': x_axis_pseudolandmarks.md
      - 'y-Axis Pseudolandmarks': y_axis_pseudolandmarks.md
      - 'Scale Features': scale_features.md
      - 'Landmark Reference Point Distribution': landmark_reference_pt_dist.md
    - 'Logical Operations':
      - 'Logical Operations-And': logical_and.md
      - 'Logical Operations-Or': logical_or.md
      - 'Logical Operations-XOr': logical_xor.md
    - 'Median Blur': median_blur.md
    - 'Morphology Functions':
      - 'Check Cycles': check_cycles.md
      - 'Find Branches': find_branch_pts.md
      - 'Find Tips': find_tips.md
      - 'Prune': prune.md
      - 'Segment Angles': segment_angle.md
      - 'Combine Segments': segment_combine.md
      - 'Segment Curvature': segment_curvature.md
      - 'Segment Euclidean Length': segment_euclidean_length.md
      - 'Segment ID': segment_id.md
      - 'Segment Insertion Angle': segment_insertion_angle.md
      - 'Segment Path Length': segment_pathlength.md
      - 'Segment Skeleton': segment_skeleton.md
      - 'Segment Sort': segment_sort.md
      - 'Segment Tangent Angle': segment_tangent_angle.md
      - 'Skeletonize': skeletonize.md
    - 'Naive Bayes Classifier': naive_bayes_classifier.md
    - 'Nonuniform Illumination Correction': nonuniform_illumination.md
    - 'Object Composition': object_composition.md
    - 'Opening': opening.md
    - 'Output Mask': output_mask.md
    - 'Outputs Class': outputs.md
    - 'Params (Debugging)': params.md
    - 'Print Image': print_image.md
    - 'Print Results': print_results.md
    - 'Plot Image': plot_image.md
    - 'Read Image': read_image.md
    - 'Read Bayer Raw Image': read_bayer.md
    - 'Rectangle Mask': rectangle_mask.md
    - 'Report Size Marker': report_size_marker.md
    - 'Rescale': transform_rescale.md
    - 'Resize': resize.md
    - 'Region of Interest Tools':
      - 'Create a Circular ROI': roi_circle.md
      - 'Create an Elliptical ROI': roi_ellipse.md
      - 'Create a Rectangular ROI': roi_rectangle.md
      - 'Create a Custom ROI': roi_custom.md
      - 'Create ROI from Binary Image': roi_from_binary_image.md
      - 'Create Multi ROIs': 'roi_multi.md'
      - 'Filter Objects by ROI': roi_objects.md
    - 'Rotate': rotate2.md
    - 'Shift Image': shift.md
    - 'Thresholding Methods':
      - 'Binary Threshold': binary_threshold.md
      - 'Custom Range Threshold': custom_range_threshold.md
      - 'Gaussian Adaptive Threshold': gaussian_threshold.md
      - 'Mean Adaptive Threshold': mean_threshold.md
      - 'Otsu Auto Threshold': otsu_threshold.md
      - 'Triangle Auto Threshold': triangle_threshold.md
      - 'Texture Threshold': texture_threshold.md
    - 'Visualization Methods':
        - 'Colorize Masks': visualize_colorize_masks.md
        - 'Histogram': visualize_histogram.md
        - 'Pseudocolor': visualize_pseudocolor.md
    - 'Watershed Segmentation': watershed.md
    - 'Within Frame': within_frame.md
  - 'Package plantcv.learn':
    - 'Naive Bayes': naive_bayes.md
    - 'Naive Bayes Multiclass': naive_bayes_multiclass.md
  - 'Package plantcv.parallel':
      - 'Job Builder': job_builder.md
      - 'Metadata Parser': metadata_parser.md
      - 'Multiprocess': mutliprocess.md
      - 'Process Results': process_results.md
      - 'Workflow Parallelization': pipeline_parallel.md
  - 'Add-on Packages':
    - 'Hyperspectral': https://plantcv.readthedocs.io/projects/hyperspectral
  - 'Accessory tools': tools.md
markdown_extensions:
  - toc:
      permalink: True
  - admonition
